###############################################################
# Wolfram Schneider, Aug 2008
#
# Get and convert OpenStreetMap.org data to BBBike
#
# For more information about BBBike, visit http://www.bbbike.de
#
# $Id: Makefile.osm,v 1.75 2009/04/11 09:46:58 wosch Exp $


OSMBIKE_DATA=	data-osm.tgz
DOWNLOADOSM=	./miscsrc/downloadosm --debug=0 --step=0.02
OSM2BBD=	perl ./miscsrc/osm2bbd -ignore-unhandled -ignore-underline --debug=0 -f -map bbbike
NICE=		nice -n 5
GXARGS=		`which gxargs xargs | head -1`

BBBIKE_WEB_DIR= /usr/local/www/elsif.de/bbbike
OSM_DIR=	osm
DATA_OSM_DIR=	data-osm
CITIES=		\
	Aachen \
	Amsterdam \
	Austin \
	Barcelona \
	Basel \
	Berlin \
	Bielefeld \
	Bonn \
	Boulder \
	BrandenburgHavel \
	Bremen \
	Budapest \
	Cambridge \
	CambridgeMa \
	Chemnitz \
	Chicago \
	Colmar \
	Copenhagen \
	Cottbus \
	Cracow \
	CraterLake \
	Danzig \
	Davis \
	Dresden \
	Duesseldorf \
	Erfurt \
	Erlangen \
	Frankfurt \
	FrankfurtOder \
	Freiburg \
	Goerlitz \
	Goettingen \
	Hamburg \
	Hannover \
	Jena \
	Karlsruhe \
	Koeln \
	Laibach \
	Leipzig \
	London \
	Luebeck \
	Mainz \
	Miami \
	Muenster \
	New_York \
	PaloAlto \
	Paris \
	Portland \
	Prag \
	Providence \
	Rostock \
	Ruegen \
	San_Francisco \
	Santa_Cruz \
	Seattle \
	Stettin \
	Strassburg \
	Toronto \
	Turin \
	Vancouver \
	WarenMueritz \
	Wien \
	Zagreb \
	Zuerich \
	Kaunas \
	Riga \
	Reval \
	SanktPetersburg \
	Helsinki \
	Stockholm \
	Oslo \
	Dublin \
	Sofia \
	Sarajewo \
	Kiew \
	Bruessel \
	Groningen \
	Montreal \
	DenHaag \
	Rotterdam \


all: help

tarball: convert-workarounds
	tar cf - data-osm | gzip > ${OSMBIKE_DATA}.tmp
	mv -f ${OSMBIKE_DATA}.tmp ${OSMBIKE_DATA}

cities: 
	${MAKE} _cities
	${MAKE} _cities
	${MAKE} _cities

_cities: 
	@for i in ${CITIES}; do \
	    ${MAKE} -f Makefile.osm $$i-download || \
	    ${MAKE} -f Makefile.osm $$i-download || \
	    ${MAKE} -f Makefile.osm $$i-download || \
	    ${MAKE} -f Makefile.osm $$i-download || \
	    ${MAKE} -f Makefile.osm $$i-download || \
		echo "please run me again: $$i"; \
	done


# using GNU xargs -P parallel
convert: 
	rm -rf data-osm.old
	if test -e data-osm; then mv data-osm data-osm.old; fi
	mkdir -p data-osm
	echo ${CITIES} " " | perl -npe 's/\s+/-convert /g' | ${NICE} ${GXARGS} -n 1 -P 4 ${MAKE} -f Makefile.osm

# massive parallel
convert.old: 
	rm -rf data-osm.old
	if test -e data-osm; then mv data-osm data-osm.old; fi
	mkdir -p data-osm
	for i in ${CITIES}; do ${NICE} ${MAKE} -f Makefile.osm "$$i"-convert & done; wait

convert-workarounds: osm2bbd-postprocess osm2bbd-workarounds green-ways missing-files cleanup-files

osm2bbd-workarounds opensearch: opensearch-bbbike
	for city in ${CITIES}; do \
		../bbbike-macos/bin/strasse-str data-osm/$$city/strassen; \
		../bbbike-macos/bin/berlin-coords-data data-osm/$$city/strassen > data-osm/$$city/Berlin.coords.data; \
		../bbbike-macos/bin/opensearch-suggestion < data-osm/$$city/strassen > data-osm/$$city/opensearch.streetnames; \
	done

opensearch-bbbike:
	../bbbike-macos/bin/opensearch-suggestion --input-charset=iso-8859-1 < data/strassen > data/opensearch.streetnames


osm2bbd-postprocess:
	for city in ${CITIES}; do \
		./miscsrc/osm2bbd-postprocess -only-largest-city-is-center -skip-inaccessible-streets data-osm/$$city; \
	done


missing-files:
	@for i in data-osm/*; do (cd $$i && touch ubahn ubahnhof sbahn sbahnhof rbahn rbahnhof Berlin.coords.data Potsdam.coords.data plaetze flaechen wasserstrassen); done # workaround for bug in osm2bbd

cleanup-files:
	#rm -f data-osm/*/meta.*
	rm -f data-osm/*/_*
	rm -f data-osm/*/*.bak

green-ways:
	for i in data-osm/*; do (cd $$i && perl -npe 's/^\s/XYZ\t/; s/RW1/green2/g' radwege_exact > green); done

# bbbike @ Copenhagen
Copenhagen: Copenhagen-download Copenhagen-convert
Copenhagen-download: 
	mkdir -p ${OSM_DIR}/Copenhagen
	${DOWNLOADOSM} -o ${OSM_DIR}/Copenhagen -- 12.275 55.549 12.702 55.831
Copenhagen-convert:
	${OSM2BBD} -centerdelta 12.44,55.56 -lang en -o ${DATA_OSM_DIR}/Copenhagen ${OSM_DIR}/Copenhagen

# bbbike @ Karlsruhe
Karlsruhe: Karlsruhe-download Karlsruhe-convert
Karlsruhe-download:
	mkdir -p ${OSM_DIR}/Karlsruhe
	${DOWNLOADOSM} -o ${OSM_DIR}/Karlsruhe -- 8.295 48.964 8.478 49.126
Karlsruhe-convert:
	${OSM2BBD} -centerdelta 8.275,48.894 -o ${DATA_OSM_DIR}/Karlsruhe ${OSM_DIR}/Karlsruhe

# bbbike @ San Francisco
San_Francisco: San_Francisco-download San_Francisco-convert
San_Francisco-download:
	mkdir -p ${OSM_DIR}/San_Francisco
	${DOWNLOADOSM} -o ${OSM_DIR}/San_Francisco -- -122.527 37.594 -122.351 37.811
San_Francisco-convert:
	${OSM2BBD} -lang en -centerdelta -122.55,37.67 -o ${DATA_OSM_DIR}/San_Francisco ${OSM_DIR}/San_Francisco

# bbbike @ Santa Cruz
Santa_Cruz: Santa_Cruz-download Santa_Cruz-convert
Santa_Cruz-download:
	mkdir -p ${OSM_DIR}/Santa_Cruz
	${DOWNLOADOSM} -o ${OSM_DIR}/Santa_Cruz -- -122.087 36.941 -121.917 37.013
Santa_Cruz-convert:
	${OSM2BBD} -lang en -centerdelta -122.12,36.845 -o ${DATA_OSM_DIR}/Santa_Cruz ${OSM_DIR}/Santa_Cruz

# bbbike @ Basel
Basel: Basel-download Basel-convert
Basel-download:
	mkdir -p ${OSM_DIR}/Basel
	${DOWNLOADOSM} -o ${OSM_DIR}/Basel -- 7.5298 47.5128 7.6823 47.5943
Basel-convert:
	${OSM2BBD} -centerdelta 7.47,47.44 -o ${DATA_OSM_DIR}/Basel ${OSM_DIR}/Basel

# bbbike @ Berlin
Berlin: Berlin-download Berlin-convert
Berlin-download:
	mkdir -p ${OSM_DIR}/Berlin
	${DOWNLOADOSM} -o ${OSM_DIR}/Berlin -- 13.0109 52.3376 13.7613 52.6753
Berlin-convert:
	${OSM2BBD} -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/Berlin ${OSM_DIR}/Berlin


# bbbike @ Amsterdam
Amsterdam: Amsterdam-download Amsterdam-convert
Amsterdam-download:
	mkdir -p ${OSM_DIR}/Amsterdam
	${DOWNLOADOSM} -o ${OSM_DIR}/Amsterdam -- 4.7982 52.3206 5.0265 52.4309
Amsterdam-convert:
	${OSM2BBD} -lang en -centerdelta 4.77,52.25 -o ${DATA_OSM_DIR}/Amsterdam ${OSM_DIR}/Amsterdam

# bbbike @ Erlangen
Erlangen: Erlangen-download Erlangen-convert
Erlangen-download:
	mkdir -p ${OSM_DIR}/Erlangen
	${DOWNLOADOSM} -o ${OSM_DIR}/Erlangen -- 10.9636 49.5208 11.0606 49.6199
Erlangen-convert:
	${OSM2BBD} -centerdelta 10.87,49.48 -o ${DATA_OSM_DIR}/Erlangen ${OSM_DIR}/Erlangen

# bbbike @ Freiburg
Freiburg: Freiburg-download Freiburg-convert
Freiburg-download:
	mkdir -p ${OSM_DIR}/Freiburg
	${DOWNLOADOSM} -o ${OSM_DIR}/Freiburg -- 7.7758 47.9677 7.9087 48.0393
Freiburg-convert:
	${OSM2BBD} -centerdelta 7.73,47.88 -o ${DATA_OSM_DIR}/Freiburg ${OSM_DIR}/Freiburg

# bbbike @ Hannover
Hannover: Hannover-download Hannover-convert
Hannover-download:
	mkdir -p ${OSM_DIR}/Hannover
	${DOWNLOADOSM} -o ${OSM_DIR}/Hannover -- 9.583 52.308 9.92 52.473
Hannover-convert:
	${OSM2BBD} -centerdelta 9.61,52.25 -o ${DATA_OSM_DIR}/Hannover ${OSM_DIR}/Hannover

# bbbike @ Colmar
Colmar: Colmar-download Colmar-convert
Colmar-download:
	mkdir -p ${OSM_DIR}/Colmar
	${DOWNLOADOSM} -o ${OSM_DIR}/Colmar -- 7.305 48.0471 7.4086 48.1236
Colmar-convert:
	${OSM2BBD} -centerdelta 7.23,47.96 -o ${DATA_OSM_DIR}/Colmar ${OSM_DIR}/Colmar

# bbbike @ Zuerich
Zuerich: Zuerich-download Zuerich-convert
Zuerich-download:
	mkdir -p ${OSM_DIR}/Zuerich
	${DOWNLOADOSM} -o ${OSM_DIR}/Zuerich -- 8.4483 47.3437 8.6271 47.4185
Zuerich-convert:
	${OSM2BBD} -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/Zuerich ${OSM_DIR}/Zuerich


# bbbike @ Portland
Portland: Portland-download Portland-convert
Portland-download:
	mkdir -p ${OSM_DIR}/Portland
	#${DOWNLOADOSM} -o ${OSM_DIR}/Portland -- -122.99 45.74 -122.37 45.34
	${DOWNLOADOSM} -o ${OSM_DIR}/Portland -- -122.81 45.43 -122.53 45.59
Portland-convert:
	${OSM2BBD} -lang en -centerdelta -122.80,45.40 -o ${DATA_OSM_DIR}/Portland ${OSM_DIR}/Portland

# bbbike @ Wien
Wien: Wien-download Wien-convert
Wien-download:
	mkdir -p ${OSM_DIR}/Wien
	${DOWNLOADOSM} -o ${OSM_DIR}/Wien -- 16.2779 48.1592 16.4976 48.2636
Wien-convert:
	${OSM2BBD} -centerdelta 16.24,48.09 -o ${DATA_OSM_DIR}/Wien ${OSM_DIR}/Wien

# bbbike @ Laibach
Laibach: Laibach-download Laibach-convert
Laibach-download:
	mkdir -p ${OSM_DIR}/Laibach
	${DOWNLOADOSM} -o ${OSM_DIR}/Laibach -- 14.43 46.01 14.64 46.13
Laibach-convert:
	${OSM2BBD} -centerdelta 14.39,45.93 -o ${DATA_OSM_DIR}/Laibach ${OSM_DIR}/Laibach

# bbbike @ Cracow
Cracow: Cracow-download Cracow-convert
Cracow-download:
	mkdir -p ${OSM_DIR}/Cracow
	${DOWNLOADOSM} -o ${OSM_DIR}/Cracow -- 19.88 50.02 20.00 50.09
Cracow-convert:
	${OSM2BBD} -lang en -centerdelta 19.82,49.94 -o ${DATA_OSM_DIR}/Cracow ${OSM_DIR}/Cracow

# bbbike @ Cambridge
Cambridge: Cambridge-download Cambridge-convert
Cambridge-download:
	mkdir -p ${OSM_DIR}/Cambridge
	${DOWNLOADOSM} -o ${OSM_DIR}/Cambridge -- 0.0593 52.1708 0.2018 52.2577
Cambridge-convert:
	${OSM2BBD} -lang en -centerdelta 0.00,52.085 -o ${DATA_OSM_DIR}/Cambridge ${OSM_DIR}/Cambridge

rsync-source:
	rsync -azv -C --exclude osm   --safe-links  $$HOME/projects/bbbike/ srand.de:/usr/local/www/srand.de/bbbike
	rsync -azv -C --exclude osm   --safe-links  $$HOME/projects/bbbike/ elsif.de:/usr/local/www/elsif.de/bbbike

rsync-osm:
	rsync -azv --delete --max-delete=512 data-osm osm elsif.de:bbbike

# bbbike @ Austin
Austin: Austin-download Austin-convert
Austin-download:
	mkdir -p ${OSM_DIR}/Austin
	${DOWNLOADOSM} -o ${OSM_DIR}/Austin -- -97.798 30.216 -97.675 30.316
Austin-convert:
	${OSM2BBD} -lang en -centerdelta -97.87,30.15 -o ${DATA_OSM_DIR}/Austin ${OSM_DIR}/Austin

# bbbike @ New York
New_York: New_York-download New_York-convert
New_York-download:
	mkdir -p ${OSM_DIR}/New_York
	${DOWNLOADOSM} -o ${OSM_DIR}/New_York -- -74.063 40.67 -73.894 40.827
New_York-convert:
	${OSM2BBD} -lang en -centerdelta -74.12,40.59 -o ${DATA_OSM_DIR}/New_York ${OSM_DIR}/New_York

# bbbike @ Toronto
Toronto: Toronto-download Toronto-convert
Toronto-download:
	mkdir -p ${OSM_DIR}/Toronto
	${DOWNLOADOSM} -o ${OSM_DIR}/Toronto -- -79.674 43.602 -79.077 43.849
Toronto-convert:
	${OSM2BBD} -lang en -centerdelta -79.674,43.602 -o ${DATA_OSM_DIR}/Toronto ${OSM_DIR}/Toronto


##############################################################################################
# bbbike @ Aachen
Aachen: Aachen-download Aachen-convert
Aachen-download:
	mkdir -p ${OSM_DIR}/Aachen
	${DOWNLOADOSM} -o ${OSM_DIR}/Aachen -- 6.0388 50.7388 6.1549 50.8076
Aachen-convert:
	${OSM2BBD} -centerdelta 6.03,50.73 -o ${DATA_OSM_DIR}/Aachen ${OSM_DIR}/Aachen

# bbbike @ Bielefeld
Bielefeld: Bielefeld-download Bielefeld-convert
Bielefeld-download:
	mkdir -p ${OSM_DIR}/Bielefeld
	${DOWNLOADOSM} -o ${OSM_DIR}/Bielefeld -- 8.399 51.946 8.657 52.071
Bielefeld-convert:
	${OSM2BBD} -centerdelta 8.39,51.94 -o ${DATA_OSM_DIR}/Bielefeld ${OSM_DIR}/Bielefeld

# bbbike @ Bonn
Bonn: Bonn-download Bonn-convert
Bonn-download:
	mkdir -p ${OSM_DIR}/Bonn
	${DOWNLOADOSM} -o ${OSM_DIR}/Bonn -- 6.971 50.621 7.289 50.813
Bonn-convert:
	${OSM2BBD} -centerdelta 6.97,50.62 -o ${DATA_OSM_DIR}/Bonn ${OSM_DIR}/Bonn

# bbbike @ Bremen
Bremen: Bremen-download Bremen-convert
Bremen-download:
	mkdir -p ${OSM_DIR}/Bremen
	${DOWNLOADOSM} -o ${OSM_DIR}/Bremen -- 8.704 53.007 9.001 53.137
Bremen-convert:
	${OSM2BBD} -centerdelta 8.70,53.00 -o ${DATA_OSM_DIR}/Bremen ${OSM_DIR}/Bremen

# bbbike @ Dresden
Dresden: Dresden-download Dresden-convert
Dresden-download:
	mkdir -p ${OSM_DIR}/Dresden
	${DOWNLOADOSM} -o ${OSM_DIR}/Dresden -- 13.61 50.97 13.922 51.119
Dresden-convert:
	${OSM2BBD} -centerdelta 13.61,50.97 -o ${DATA_OSM_DIR}/Dresden ${OSM_DIR}/Dresden

# bbbike @ Duesseldorf
Duesseldorf: Duesseldorf-download Duesseldorf-convert
Duesseldorf-download:
	mkdir -p ${OSM_DIR}/Duesseldorf
	${DOWNLOADOSM} -o ${OSM_DIR}/Duesseldorf -- 6.637 51.145 6.959 51.295
Duesseldorf-convert:
	${OSM2BBD} -centerdelta 6.637,51.145 -o ${DATA_OSM_DIR}/Duesseldorf ${OSM_DIR}/Duesseldorf

# bbbike @ Erfurt
Erfurt: Erfurt-download Erfurt-convert
Erfurt-download:
	mkdir -p ${OSM_DIR}/Erfurt
	${DOWNLOADOSM} -o ${OSM_DIR}/Erfurt -- 10.969 50.9454 11.0991 51.0087
Erfurt-convert:
	${OSM2BBD} -centerdelta 10.969,50.9454 -o ${DATA_OSM_DIR}/Erfurt ${OSM_DIR}/Erfurt

# bbbike @ Frankfurt
Frankfurt: Frankfurt-download Frankfurt-convert
Frankfurt-download:
	mkdir -p ${OSM_DIR}/Frankfurt
	${DOWNLOADOSM} -o ${OSM_DIR}/Frankfurt -- 8.44 50.02 8.979 50.185
Frankfurt-convert:
	${OSM2BBD} -centerdelta 8.66,50.10 -o ${DATA_OSM_DIR}/Frankfurt ${OSM_DIR}/Frankfurt

# bbbike @ Goettingen
Goettingen: Goettingen-download Goettingen-convert
Goettingen-download:
	mkdir -p ${OSM_DIR}/Goettingen
	${DOWNLOADOSM} -o ${OSM_DIR}/Goettingen -- 9.8519 51.494 9.9917 51.5818
Goettingen-convert:
	${OSM2BBD} -centerdelta 9.8519,51.494 -o ${DATA_OSM_DIR}/Goettingen ${OSM_DIR}/Goettingen

# bbbike @ Hamburg
Hamburg: Hamburg-download Hamburg-convert
Hamburg-download:
	mkdir -p ${OSM_DIR}/Hamburg
	${DOWNLOADOSM} -o ${OSM_DIR}/Hamburg -- 9.77 53.426 10.24 53.663
Hamburg-convert:
	${OSM2BBD} -centerdelta 9.77,53.426 -o ${DATA_OSM_DIR}/Hamburg ${OSM_DIR}/Hamburg

# bbbike @ Jena
Jena: Jena-download Jena-convert
Jena-download:
	mkdir -p ${OSM_DIR}/Jena
	${DOWNLOADOSM} -o ${OSM_DIR}/Jena -- 11.5241 50.8597 11.6696 50.9705
Jena-convert:
	${OSM2BBD} -centerdelta 11.52,50.85 -o ${DATA_OSM_DIR}/Jena ${OSM_DIR}/Jena

# bbbike @ Koeln
Koeln: Koeln-download Koeln-convert
Koeln-download:
	mkdir -p ${OSM_DIR}/Koeln
	${DOWNLOADOSM} -o ${OSM_DIR}/Koeln -- 6.823 50.865 7.108 51.015
Koeln-convert:
	${OSM2BBD} -centerdelta 6.82,50.86 -o ${DATA_OSM_DIR}/Koeln ${OSM_DIR}/Koeln

# bbbike @ Leipzig
Leipzig: Leipzig-download Leipzig-convert
Leipzig-download:
	mkdir -p ${OSM_DIR}/Leipzig
	${DOWNLOADOSM} -o ${OSM_DIR}/Leipzig -- 12.271 51.27 12.502 51.4
Leipzig-convert:
	${OSM2BBD} -centerdelta 12.27,51.27 -o ${DATA_OSM_DIR}/Leipzig ${OSM_DIR}/Leipzig

# bbbike @ Luebeck
Luebeck: Luebeck-download Luebeck-convert
Luebeck-download:
	mkdir -p ${OSM_DIR}/Luebeck
	${DOWNLOADOSM} -o ${OSM_DIR}/Luebeck -- 10.574 53.82 10.806 53.933
Luebeck-convert:
	${OSM2BBD} -centerdelta 10.57,53.82 -o ${DATA_OSM_DIR}/Luebeck ${OSM_DIR}/Luebeck

# bbbike @ Mainz
Mainz: Mainz-download Mainz-convert
Mainz-download:
	mkdir -p ${OSM_DIR}/Mainz
	${DOWNLOADOSM} -o ${OSM_DIR}/Mainz -- 8.1339 49.9325 8.4123 50.1077
Mainz-convert:
	${OSM2BBD} -centerdelta 8.13,49.93 -o ${DATA_OSM_DIR}/Mainz ${OSM_DIR}/Mainz

# bbbike @ Muenster
Muenster: Muenster-download Muenster-convert
Muenster-download:
	mkdir -p ${OSM_DIR}/Muenster
	${DOWNLOADOSM} -o ${OSM_DIR}/Muenster -- 7.5771 51.9226 7.6873 51.9917
Muenster-convert:
	${OSM2BBD} -centerdelta 7.57,51.92 -o ${DATA_OSM_DIR}/Muenster ${OSM_DIR}/Muenster

# bbbike @ Rostock
Rostock: Rostock-download Rostock-convert
Rostock-download:
	mkdir -p ${OSM_DIR}/Rostock
	${DOWNLOADOSM} -o ${OSM_DIR}/Rostock -- 12.0204 54.0599 12.2271 54.1933
Rostock-convert:
	${OSM2BBD} -centerdelta 12.02,54.05 -o ${DATA_OSM_DIR}/Rostock ${OSM_DIR}/Rostock

# bbbike @ Strassburg
Strassburg: Strassburg-download Strassburg-convert
Strassburg-download:
	mkdir -p ${OSM_DIR}/Strassburg
	${DOWNLOADOSM} -o ${OSM_DIR}/Strassburg -- 7.6515 48.5189 7.875 48.6525
Strassburg-convert:
	${OSM2BBD} -centerdelta 7.65,48.51 -o ${DATA_OSM_DIR}/Strassburg ${OSM_DIR}/Strassburg

# bbbike @ Providence
Providence: Providence-download Providence-convert
Providence-download:
	mkdir -p ${OSM_DIR}/Providence
	${DOWNLOADOSM} -o ${OSM_DIR}/Providence -- -71.5273 41.7378 -71.3141 41.9006
Providence-convert:
	${OSM2BBD} -lang en -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/Providence ${OSM_DIR}/Providence


# bbbike @ Ruegen
Ruegen: Ruegen-download Ruegen-convert
Ruegen-download:
	mkdir -p ${OSM_DIR}/Ruegen
	${DOWNLOADOSM} -o ${OSM_DIR}/Ruegen -- 12.904 54.199 13.81 54.708
Ruegen-convert:
	${OSM2BBD} -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/Ruegen ${OSM_DIR}/Ruegen

# bbbike @ Chemnitz
Chemnitz: Chemnitz-download Chemnitz-convert
Chemnitz-download:
	mkdir -p ${OSM_DIR}/Chemnitz
	${DOWNLOADOSM} -o ${OSM_DIR}/Chemnitz -- 12.8152 50.7803 13.0154 50.8796
Chemnitz-convert:
	${OSM2BBD} -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/Chemnitz ${OSM_DIR}/Chemnitz


# bbbike @ Paris
Paris: Paris-download Paris-convert
Paris-download:
	mkdir -p ${OSM_DIR}/Paris
	${DOWNLOADOSM} -o ${OSM_DIR}/Paris -- 2.2168 48.7974 2.4681 48.9241
Paris-convert:
	${OSM2BBD} -lang en -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/Paris ${OSM_DIR}/Paris


# bbbike @ London
London: London-download London-convert
London-download:
	mkdir -p ${OSM_DIR}/London
	${DOWNLOADOSM} -o ${OSM_DIR}/London -- -0.2417 51.4403 0.023 51.5621
London-convert:
	${OSM2BBD} -lang en -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/London ${OSM_DIR}/London

# bbbike @ Zagreb
Zagreb: Zagreb-download Zagreb-convert
Zagreb-download:
	mkdir -p ${OSM_DIR}/Zagreb
	${DOWNLOADOSM} -o ${OSM_DIR}/Zagreb -- 15.8652 45.7381 16.1155 45.8511
Zagreb-convert:
	${OSM2BBD} -lang en -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/Zagreb ${OSM_DIR}/Zagreb

# bbbike @ Prag
Prag: Prag-download Prag-convert
Prag-download:
	mkdir -p ${OSM_DIR}/Prag
	${DOWNLOADOSM} -o ${OSM_DIR}/Prag -- 14.3016 50.0241 14.6009 50.1468
Prag-convert:
	${OSM2BBD} -lang en -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/Prag ${OSM_DIR}/Prag


# bbbike @ Budapest
Budapest: Budapest-download Budapest-convert
Budapest-download:
	mkdir -p ${OSM_DIR}/Budapest
	${DOWNLOADOSM} -o ${OSM_DIR}/Budapest -- 18.9482 47.434 19.1556 47.5407
Budapest-convert:
	${OSM2BBD} -lang en -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/Budapest ${OSM_DIR}/Budapest


# bbbike @ Danzig
Danzig: Danzig-download Danzig-convert
Danzig-download:
	mkdir -p ${OSM_DIR}/Danzig
	${DOWNLOADOSM} -o ${OSM_DIR}/Danzig -- 18.411 54.303 18.812 54.57
Danzig-convert:
	${OSM2BBD} -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/Danzig ${OSM_DIR}/Danzig

# bbbike @ Goerlitz
Goerlitz: Goerlitz-download Goerlitz-convert
Goerlitz-download:
	mkdir -p ${OSM_DIR}/Goerlitz
	${DOWNLOADOSM} -o ${OSM_DIR}/Goerlitz -- 14.9082 51.0989 15.0494 51.1891
Goerlitz-convert:
	${OSM2BBD} -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/Goerlitz ${OSM_DIR}/Goerlitz

# bbbike @ FrankfurtOder
FrankfurtOder: FrankfurtOder-download FrankfurtOder-convert
FrankfurtOder-download:
	mkdir -p ${OSM_DIR}/FrankfurtOder
	${DOWNLOADOSM} -o ${OSM_DIR}/FrankfurtOder -- 14.4804 52.3074 14.6026 52.3724
FrankfurtOder-convert:
	${OSM2BBD} -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/FrankfurtOder ${OSM_DIR}/FrankfurtOder

# bbbike @ Stettin
Stettin: Stettin-download Stettin-convert
Stettin-download:
	mkdir -p ${OSM_DIR}/Stettin
	${DOWNLOADOSM} -o ${OSM_DIR}/Stettin -- 14.4419 53.3575 14.7299 53.4764
Stettin-convert:
	${OSM2BBD} -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/Stettin ${OSM_DIR}/Stettin

# bbbike @ Turin
Turin: Turin-download Turin-convert
Turin-download:
	mkdir -p ${OSM_DIR}/Turin
	${DOWNLOADOSM} -o ${OSM_DIR}/Turin -- 7.6221 45.0155 7.7594 45.1106
Turin-convert:
	${OSM2BBD} -lang en -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/Turin ${OSM_DIR}/Turin

# bbbike @ Cottbus
Cottbus: Cottbus-download Cottbus-convert
Cottbus-download:
	mkdir -p ${OSM_DIR}/Cottbus
	${DOWNLOADOSM} -o ${OSM_DIR}/Cottbus -- 14.2561 51.7092 14.435 51.8101
Cottbus-convert:
	${OSM2BBD} -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/Cottbus ${OSM_DIR}/Cottbus


# bbbike @ BrandenburgHavel
BrandenburgHavel: BrandenburgHavel-download BrandenburgHavel-convert
BrandenburgHavel-download:
	mkdir -p ${OSM_DIR}/BrandenburgHavel
	${DOWNLOADOSM} -o ${OSM_DIR}/BrandenburgHavel -- 12.4647 52.3745 12.6563 52.4511
BrandenburgHavel-convert:
	${OSM2BBD} -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/BrandenburgHavel ${OSM_DIR}/BrandenburgHavel

# bbbike @ WarenMueritz
WarenMueritz: WarenMueritz-download WarenMueritz-convert
WarenMueritz-download:
	mkdir -p ${OSM_DIR}/WarenMueritz
	${DOWNLOADOSM} -o ${OSM_DIR}/WarenMueritz -- 12.5982 53.4811 12.7647 53.5488
WarenMueritz-convert:
	${OSM2BBD} -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/WarenMueritz ${OSM_DIR}/WarenMueritz

# bbbike @ Barcelona
Barcelona: Barcelona-download Barcelona-convert
Barcelona-download:
	mkdir -p ${OSM_DIR}/Barcelona
	${DOWNLOADOSM} -o ${OSM_DIR}/Barcelona -- 2.0555 41.2953 2.267 41.4718
Barcelona-convert:
	${OSM2BBD} -lang en -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/Barcelona ${OSM_DIR}/Barcelona

# bbbike @ Boulder
Boulder: Boulder-download Boulder-convert
Boulder-download:
	mkdir -p ${OSM_DIR}/Boulder
	${DOWNLOADOSM} -o ${OSM_DIR}/Boulder -- -105.3198 39.963 -105.2017 40.07
Boulder-convert:
	${OSM2BBD} -lang en -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/Boulder ${OSM_DIR}/Boulder

# bbbike @ Seattle
Seattle: Seattle-download Seattle-convert
Seattle-download:
	mkdir -p ${OSM_DIR}/Seattle
	${DOWNLOADOSM} -o ${OSM_DIR}/Seattle -- -122.4612 47.5219 -122.1851 47.6823
Seattle-convert:
	${OSM2BBD} -lang en -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/Seattle ${OSM_DIR}/Seattle

# bbbike @ Chicago
Chicago: Chicago-download Chicago-convert
Chicago-download:
	mkdir -p ${OSM_DIR}/Chicago
	${DOWNLOADOSM} -o ${OSM_DIR}/Chicago -- -87.7501 41.7789 -87.5307 41.9326
Chicago-convert:
	${OSM2BBD} -lang en -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/Chicago ${OSM_DIR}/Chicago


# bbbike @ PaloAlto
PaloAlto: PaloAlto-download PaloAlto-convert
PaloAlto-download:
	mkdir -p ${OSM_DIR}/PaloAlto
	${DOWNLOADOSM} -o ${OSM_DIR}/PaloAlto -- -122.2585 37.3661 -122.0223 37.5176
PaloAlto-convert:
	${OSM2BBD} -lang en -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/PaloAlto ${OSM_DIR}/PaloAlto

# bbbike @ CraterLake
CraterLake: CraterLake-download CraterLake-convert
CraterLake-download:
	mkdir -p ${OSM_DIR}/CraterLake
	${DOWNLOADOSM} -o ${OSM_DIR}/CraterLake -- -122.2593 42.8404 -121.9531 43.0219
CraterLake-convert:
	${OSM2BBD} -lang en -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/CraterLake ${OSM_DIR}/CraterLake


# bbbike @ Davis
Davis: Davis-download Davis-convert
Davis-download:
	mkdir -p ${OSM_DIR}/Davis
	${DOWNLOADOSM} -o ${OSM_DIR}/Davis -- -121.8085 38.5045 -121.6698 38.5942
Davis-convert:
	${OSM2BBD} -lang en -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/Davis ${OSM_DIR}/Davis

# bbbike @ CambridgeMa
CambridgeMa: CambridgeMa-download CambridgeMa-convert
CambridgeMa-download:
	mkdir -p ${OSM_DIR}/CambridgeMa
	${DOWNLOADOSM} -o ${OSM_DIR}/CambridgeMa -- -71.1986 42.3265 -71.0036 42.4285
CambridgeMa-convert:
	${OSM2BBD} -lang en -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/CambridgeMa ${OSM_DIR}/CambridgeMa

# bbbike @ Vancouver
Vancouver: Vancouver-download Vancouver-convert
Vancouver-download:
	mkdir -p ${OSM_DIR}/Vancouver
	${DOWNLOADOSM} -o ${OSM_DIR}/Vancouver -- -123.2871 49.1809 -122.9818 49.3422
Vancouver-convert:
	${OSM2BBD} -lang en -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/Vancouver ${OSM_DIR}/Vancouver


# bbbike @ Miami
Miami: Miami-download Miami-convert
Miami-download:
	mkdir -p ${OSM_DIR}/Miami
	${DOWNLOADOSM} -o ${OSM_DIR}/Miami -- -80.3244 25.6548 -80.0473 25.8567
Miami-convert:
	${OSM2BBD} -lang en -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/Miami ${OSM_DIR}/Miami



# bbbike @ Kaunas
Kaunas: Kaunas-download Kaunas-convert
Kaunas-download:
	mkdir -p ${OSM_DIR}/Kaunas
	${DOWNLOADOSM} -o ${OSM_DIR}/Kaunas -- 23.8001 54.8585 24.0157 54.9521
Kaunas-convert:
	${OSM2BBD} -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/Kaunas ${OSM_DIR}/Kaunas



# bbbike @ Riga
Riga: Riga-download Riga-convert
Riga-download:
	mkdir -p ${OSM_DIR}/Riga
	${DOWNLOADOSM} -o ${OSM_DIR}/Riga -- 23.9847 56.9117 24.2099 56.9943
Riga-convert:
	${OSM2BBD} -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/Riga ${OSM_DIR}/Riga



# bbbike @ Reval
Reval: Reval-download Reval-convert
Reval-download:
	mkdir -p ${OSM_DIR}/Reval
	${DOWNLOADOSM} -o ${OSM_DIR}/Reval -- 24.6189 59.3803 24.8744 59.4872
Reval-convert:
	${OSM2BBD} -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/Reval ${OSM_DIR}/Reval



# bbbike @ SanktPetersburg
SanktPetersburg: SanktPetersburg-download SanktPetersburg-convert
SanktPetersburg-download:
	mkdir -p ${OSM_DIR}/SanktPetersburg
	${DOWNLOADOSM} -o ${OSM_DIR}/SanktPetersburg -- 30.151 59.865 30.502 60.016
SanktPetersburg-convert:
	${OSM2BBD} -lang en -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/SanktPetersburg ${OSM_DIR}/SanktPetersburg


# bbbike @ Helsinki
Helsinki: Helsinki-download Helsinki-convert
Helsinki-download:
	mkdir -p ${OSM_DIR}/Helsinki
	${DOWNLOADOSM} -o ${OSM_DIR}/Helsinki -- 24.8391 60.1277 25.0462 60.2061
Helsinki-convert:
	${OSM2BBD} -lang en -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/Helsinki ${OSM_DIR}/Helsinki



# bbbike @ Stockholm
Stockholm: Stockholm-download Stockholm-convert
Stockholm-download:
	mkdir -p ${OSM_DIR}/Stockholm
	${DOWNLOADOSM} -o ${OSM_DIR}/Stockholm -- 17.9752 59.2945 18.1664 59.3623
Stockholm-convert:
	${OSM2BBD} -lang en -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/Stockholm ${OSM_DIR}/Stockholm


# bbbike @ Oslo
Oslo: Oslo-download Oslo-convert
Oslo-download:
	mkdir -p ${OSM_DIR}/Oslo
	${DOWNLOADOSM} -o ${OSM_DIR}/Oslo -- 10.6517 59.8831 10.8323 59.9526
Oslo-convert:
	${OSM2BBD} -lang en -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/Oslo ${OSM_DIR}/Oslo


# bbbike @ Dublin
Dublin: Dublin-download Dublin-convert
Dublin-download:
	mkdir -p ${OSM_DIR}/Dublin
	${DOWNLOADOSM} -o ${OSM_DIR}/Dublin -- -6.3485 53.2933 -6.1552 53.3867
Dublin-convert:
	${OSM2BBD} -lang en -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/Dublin ${OSM_DIR}/Dublin



# bbbike @ Sarajewo
Sarajewo: Sarajewo-download Sarajewo-convert
Sarajewo-download:
	mkdir -p ${OSM_DIR}/Sarajewo
	${DOWNLOADOSM} -o ${OSM_DIR}/Sarajewo -- 18.3664 43.8334 18.4889 43.8915
Sarajewo-convert:
	${OSM2BBD} -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/Sarajewo ${OSM_DIR}/Sarajewo



# bbbike @ Sofia
Sofia: Sofia-download Sofia-convert
Sofia-download:
	mkdir -p ${OSM_DIR}/Sofia
	${DOWNLOADOSM} -o ${OSM_DIR}/Sofia -- 23.2146 42.6445 23.4244 42.7505
Sofia-convert:
	${OSM2BBD} -lang en -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/Sofia ${OSM_DIR}/Sofia

# bbbike @ Kiew
Kiew: Kiew-download Kiew-convert
Kiew-download:
	mkdir -p ${OSM_DIR}/Kiew
	${DOWNLOADOSM} -o ${OSM_DIR}/Kiew -- 30.4236 50.3854 30.6385 50.4963
Kiew-convert:
	${OSM2BBD} -lang en -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/Kiew ${OSM_DIR}/Kiew


# bbbike @ Bruessel
Bruessel: Bruessel-download Bruessel-convert
Bruessel-download:
	mkdir -p ${OSM_DIR}/Bruessel
	${DOWNLOADOSM} -o ${OSM_DIR}/Bruessel -- 4.2614 50.7981 4.4376 50.8996
Bruessel-convert:
	${OSM2BBD} -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/Bruessel ${OSM_DIR}/Bruessel

# bbbike @ Groningen
Groningen: Groningen-download Groningen-convert
Groningen-download:
	mkdir -p ${OSM_DIR}/Groningen
	${DOWNLOADOSM} -o ${OSM_DIR}/Groningen -- 6.4602 53.1568 6.6769 53.281
Groningen-convert:
	${OSM2BBD} -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/Groningen ${OSM_DIR}/Groningen


# bbbike @ Montreal
Montreal: Montreal-download Montreal-convert
Montreal-download:
	mkdir -p ${OSM_DIR}/Montreal
	${DOWNLOADOSM} -o ${OSM_DIR}/Montreal -- -73.787 45.37 -73.404 45.607
Montreal-convert:
	${OSM2BBD} -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/Montreal ${OSM_DIR}/Montreal

# bbbike @ DenHaag
DenHaag: DenHaag-download DenHaag-convert
DenHaag-download:
	mkdir -p ${OSM_DIR}/DenHaag
	${DOWNLOADOSM} -o ${OSM_DIR}/DenHaag -- 4.2023 52.0097 4.4241 52.1288
DenHaag-convert:
	${OSM2BBD} -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/DenHaag ${OSM_DIR}/DenHaag


# bbbike @ Rotterdam
Rotterdam: Rotterdam-download Rotterdam-convert
Rotterdam-download:
	mkdir -p ${OSM_DIR}/Rotterdam
	${DOWNLOADOSM} -o ${OSM_DIR}/Rotterdam -- 4.3605 51.8601 4.6053 51.969
Rotterdam-convert:
	${OSM2BBD} -centerdelta 8.41,47.25 -o ${DATA_OSM_DIR}/Rotterdam ${OSM_DIR}/Rotterdam


##############################################################################################


create-bbbike-web-symlinks:
	cd ${BBBIKE_WEB_DIR}/cgi && \
	for city in ${CITIES}; do \
		ln -fs world.cgi $$city.cgi; \
		ln -fs world.cgi $$city.en.cgi; \
		ln -fs world.cgi.config $$city.cgi.config; \
	done
	ln -fs `pwd`/misc/index.html ${BBBIKE_WEB_DIR}
	ln -fs `pwd`/misc/world.cgi ${BBBIKE_WEB_DIR}/cgi
	ln -fs `pwd`/misc/world.cgi.config ${BBBIKE_WEB_DIR}/cgi


scp rsync rsync-tgz:
	rsync -av ${OSMBIKE_DATA} wolfram.schneider.org:www/src/bbbike

clean:
	rm -rf data-osm
	mkdir data-osm

dist-clean devel-clean distclean: clean
	rm -rf osm
	mkdir -p osm

help:
	@echo "usage: make [ help | cities | convert | rsync-tgz | rsync-source | rsync-osm ]"
	@echo "            [ tarball | clean | dist-clean | create-bbbike-web-symlinks | opensearch ]"
	@echo ""
	@echo "            [ ${CITIES} ]"

